alter table public.tracks
  add column if not exists id bigint generated by default as identity,
  add column if not exists circuit_name text,
  add column if not exists display_name text,
  add column if not exists slug text,
  add column if not exists grand_prix_name text,
  add column if not exists country text,
  add column if not exists country_code text,
  add column if not exists city text,
  add column if not exists region text,
  add column if not exists timezone text,
  add column if not exists latitude numeric(9, 6),
  add column if not exists longitude numeric(9, 6),
  add column if not exists elevation_metres integer,
  add column if not exists circuit_type text,
  add column if not exists ownership_type text,
  add column if not exists promoter_name text,
  add column if not exists website_url text,
  add column if not exists track_map_url text,
  add column if not exists hero_image_url text,

  -- Physical circuit specification
  add column if not exists lap_length_km numeric(6, 3),
  add column if not exists race_laps integer,
  add column if not exists race_distance_km numeric(7, 3),
  add column if not exists corner_count integer,
  add column if not exists left_corner_count integer,
  add column if not exists right_corner_count integer,
  add column if not exists drs_zone_count integer,
  add column if not exists longest_straight_metres integer,
  add column if not exists minimum_track_width_metres numeric(5, 2),
  add column if not exists maximum_track_width_metres numeric(5, 2),
  add column if not exists pit_lane_length_metres integer,
  add column if not exists pit_lane_speed_limit_kph integer,
  add column if not exists racing_direction text,
  add column if not exists surface_type text,
  add column if not exists surface_age_years integer,
  add column if not exists surface_bumpiness_rating integer not null default 50,
  add column if not exists surface_grip_rating integer not null default 50,
  add column if not exists track_evolution_rating integer not null default 50,

  -- Performance characteristics (0-100)
  add column if not exists average_speed_rating integer not null default 50,
  add column if not exists top_speed_rating integer not null default 50,
  add column if not exists low_speed_corner_rating integer not null default 50,
  add column if not exists medium_speed_corner_rating integer not null default 50,
  add column if not exists high_speed_corner_rating integer not null default 50,
  add column if not exists braking_demand_rating integer not null default 50,
  add column if not exists traction_demand_rating integer not null default 50,
  add column if not exists aerodynamic_demand_rating integer not null default 50,
  add column if not exists downforce_level text,
  add column if not exists power_sensitivity_rating integer not null default 50,
  add column if not exists fuel_sensitivity_rating integer not null default 50,
  add column if not exists ers_sensitivity_rating integer not null default 50,
  add column if not exists cooling_demand_rating integer not null default 50,
  add column if not exists tyre_stress_rating integer not null default 50,
  add column if not exists front_tyre_stress_rating integer not null default 50,
  add column if not exists rear_tyre_stress_rating integer not null default 50,
  add column if not exists tyre_warmup_difficulty_rating integer not null default 50,
  add column if not exists overtaking_difficulty_rating integer not null default 50,
  add column if not exists dirty_air_sensitivity_rating integer not null default 50,
  add column if not exists driver_difficulty_rating integer not null default 50,
  add column if not exists setup_difficulty_rating integer not null default 50,
  add column if not exists reliability_demand_rating integer not null default 50,
  add column if not exists gearbox_demand_rating integer not null default 50,
  add column if not exists suspension_demand_rating integer not null default 50,
  add column if not exists brake_wear_rating integer not null default 50,
  add column if not exists safety_car_probability_rating integer not null default 50,
  add column if not exists virtual_safety_car_probability_rating integer not null default 50,
  add column if not exists red_flag_probability_rating integer not null default 25,

  -- Climate and event conditions
  add column if not exists climate_type text,
  add column if not exists typical_air_temperature_c numeric(5, 2),
  add column if not exists typical_track_temperature_c numeric(5, 2),
  add column if not exists typical_humidity_percent numeric(5, 2),
  add column if not exists rain_probability_percent numeric(5, 2),
  add column if not exists extreme_heat_risk_rating integer not null default 25,
  add column if not exists storm_risk_rating integer not null default 25,
  add column if not exists wind_sensitivity_rating integer not null default 50,
  add column if not exists visibility_risk_rating integer not null default 25,
  add column if not exists drainage_rating integer not null default 50,
  add column if not exists night_race_capable boolean not null default false,
  add column if not exists permanent_lighting boolean not null default false,

  -- FIA/F1 eligibility and homologation
  add column if not exists eligible_for_f1 boolean not null default false,
  add column if not exists eligibility_status text not null default 'unassessed',
  add column if not exists eligibility_score integer not null default 0,
  add column if not exists fia_grade text,
  add column if not exists fia_grade_one_required boolean not null default true,
  add column if not exists fia_homologation_status text not null default 'unknown',
  add column if not exists fia_homologation_expiry_date date,
  add column if not exists last_fia_inspection_date date,
  add column if not exists next_fia_inspection_due_date date,
  add column if not exists safety_standard_rating integer not null default 50,
  add column if not exists barrier_standard_rating integer not null default 50,
  add column if not exists runoff_adequacy_rating integer not null default 50,
  add column if not exists debris_fence_rating integer not null default 50,
  add column if not exists marshal_post_coverage_rating integer not null default 50,
  add column if not exists race_control_rating integer not null default 50,
  add column if not exists medical_centre_rating integer not null default 50,
  add column if not exists emergency_response_rating integer not null default 50,
  add column if not exists helicopter_access_available boolean not null default false,
  add column if not exists hospital_transfer_plan_approved boolean not null default false,
  add column if not exists pit_garage_count integer,
  add column if not exists pit_garage_capacity_adequate boolean not null default false,
  add column if not exists paddock_capacity_rating integer not null default 50,
  add column if not exists scrutineering_facility_rating integer not null default 50,
  add column if not exists parc_ferme_capacity_rating integer not null default 50,
  add column if not exists timing_system_rating integer not null default 50,
  add column if not exists broadcast_infrastructure_rating integer not null default 50,
  add column if not exists power_resilience_rating integer not null default 50,
  add column if not exists drainage_compliance boolean not null default false,
  add column if not exists lighting_compliance boolean not null default false,
  add column if not exists environmental_approval_status text not null default 'unknown',
  add column if not exists noise_restriction_status text not null default 'unknown',
  add column if not exists regulatory_issues text,
  add column if not exists required_safety_upgrades text,
  add column if not exists required_infrastructure_upgrades text,

  -- Commercial and logistical calendar qualification
  add column if not exists promoter_contract_status text not null default 'none',
  add column if not exists promoter_contract_start_year integer,
  add column if not exists promoter_contract_end_year integer,
  add column if not exists hosting_fee_usd_millions numeric(10, 2),
  add column if not exists government_support_rating integer not null default 50,
  add column if not exists commercial_viability_rating integer not null default 50,
  add column if not exists fan_demand_rating integer not null default 50,
  add column if not exists global_market_value_rating integer not null default 50,
  add column if not exists attendance_capacity integer,
  add column if not exists expected_attendance integer,
  add column if not exists hospitality_capacity_rating integer not null default 50,
  add column if not exists hotel_capacity_rating integer not null default 50,
  add column if not exists airport_access_rating integer not null default 50,
  add column if not exists public_transport_rating integer not null default 50,
  add column if not exists freight_access_rating integer not null default 50,
  add column if not exists paddock_logistics_rating integer not null default 50,
  add column if not exists calendar_geography_fit_rating integer not null default 50,
  add column if not exists sustainability_rating integer not null default 50,
  add column if not exists local_community_support_rating integer not null default 50,
  add column if not exists political_stability_rating integer not null default 50,
  add column if not exists event_security_rating integer not null default 50,

  -- Calendar state and future candidacy
  add column if not exists calendar_status text not null default 'not_on_calendar',
  add column if not exists is_on_2026_calendar boolean not null default false,
  add column if not exists calendar_round_2026 integer,
  add column if not exists event_status_2026 text,
  add column if not exists sprint_event_2026 boolean not null default false,
  add column if not exists future_candidate boolean not null default false,
  add column if not exists candidate_priority integer not null default 0,
  add column if not exists candidate_readiness_rating integer not null default 0,
  add column if not exists earliest_possible_entry_year integer,
  add column if not exists replacement_track_capable boolean not null default false,
  add column if not exists temporary_event_capable boolean not null default false,
  add column if not exists calendar_rotation_candidate boolean not null default false,
  add column if not exists exclusion_reason text,
  add column if not exists candidacy_notes text,

  -- History and game metadata
  add column if not exists first_grand_prix_year integer,
  add column if not exists most_recent_grand_prix_year integer,
  add column if not exists total_f1_grands_prix integer not null default 0,
  add column if not exists lap_record_driver text,
  add column if not exists lap_record_time text,
  add column if not exists lap_record_year integer,
  add column if not exists player_popularity_rating integer not null default 50,
  add column if not exists ai_calendar_preference_rating integer not null default 50,
  add column if not exists notes text,
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.tracks'::regclass and contype = 'p'
  ) then
    alter table public.tracks alter column id set not null;
    alter table public.tracks add constraint tracks_pkey primary key (id);
  end if;
end
$$;

create unique index if not exists tracks_slug_unique_idx on public.tracks(slug);
create index if not exists tracks_2026_calendar_idx
  on public.tracks(is_on_2026_calendar, calendar_round_2026);
create index if not exists tracks_future_candidate_idx
  on public.tracks(future_candidate, candidate_priority);
create index if not exists tracks_eligibility_idx
  on public.tracks(eligible_for_f1, eligibility_status);

-- Current official 2026 venues, including venues whose scheduled event changed.
insert into public.tracks (
  circuit_name, display_name, slug, grand_prix_name, country, country_code, city,
  circuit_type, eligible_for_f1, eligibility_status, eligibility_score, fia_grade,
  fia_homologation_status, calendar_status, is_on_2026_calendar,
  calendar_round_2026, event_status_2026, future_candidate, replacement_track_capable
)
values
  ('Albert Park Grand Prix Circuit', 'Albert Park', 'albert-park', 'Australian Grand Prix', 'Australia', 'AUS', 'Melbourne', 'temporary_street', true, 'calendar_approved', 100, '1', 'approved', 'confirmed_2026', true, 1, 'completed', false, true),
  ('Shanghai International Circuit', 'Shanghai', 'shanghai', 'Chinese Grand Prix', 'China', 'CHN', 'Shanghai', 'permanent', true, 'calendar_approved', 100, '1', 'approved', 'confirmed_2026', true, 2, 'completed', false, true),
  ('Suzuka International Racing Course', 'Suzuka', 'suzuka', 'Japanese Grand Prix', 'Japan', 'JPN', 'Suzuka', 'permanent', true, 'calendar_approved', 100, '1', 'approved', 'confirmed_2026', true, 3, 'completed', false, true),
  ('Jeddah Corniche Circuit', 'Jeddah', 'jeddah', 'Saudi Arabian Grand Prix', 'Saudi Arabia', 'SAU', 'Jeddah', 'street', true, 'previously_approved', 90, '1', 'approved', 'cancelled_2026', false, null, 'called_off', false, true),
  ('Bahrain International Circuit', 'Sakhir', 'sakhir', 'Bahrain Grand Prix', 'Bahrain', 'BHR', 'Sakhir', 'permanent', true, 'previously_approved', 100, '1', 'approved', 'replaced_2026', false, null, 'venue_replaced', false, true),
  ('Miami International Autodrome', 'Miami', 'miami', 'Miami Grand Prix', 'United States', 'USA', 'Miami Gardens', 'temporary_street', true, 'calendar_approved', 100, '1', 'approved', 'confirmed_2026', true, 4, 'completed', false, true),
  ('Circuit Gilles-Villeneuve', 'Montreal', 'montreal', 'Canadian Grand Prix', 'Canada', 'CAN', 'Montreal', 'temporary_street', true, 'calendar_approved', 100, '1', 'approved', 'confirmed_2026', true, 5, 'completed', false, true),
  ('Circuit de Monaco', 'Monaco', 'monaco', 'Monaco Grand Prix', 'Monaco', 'MCO', 'Monte Carlo', 'street', true, 'calendar_approved', 100, '1', 'approved', 'confirmed_2026', true, 6, 'completed', false, false),
  ('Circuit de Barcelona-Catalunya', 'Barcelona-Catalunya', 'barcelona-catalunya', 'Barcelona-Catalunya Grand Prix', 'Spain', 'ESP', 'Montmelo', 'permanent', true, 'calendar_approved', 100, '1', 'approved', 'confirmed_2026', true, 7, 'completed', false, true),
  ('Red Bull Ring', 'Spielberg', 'spielberg', 'Austrian Grand Prix', 'Austria', 'AUT', 'Spielberg', 'permanent', true, 'calendar_approved', 100, '1', 'approved', 'confirmed_2026', true, 8, 'completed', false, true),
  ('Silverstone Circuit', 'Silverstone', 'silverstone', 'British Grand Prix', 'United Kingdom', 'GBR', 'Silverstone', 'permanent', true, 'calendar_approved', 100, '1', 'approved', 'confirmed_2026', true, 9, 'completed', false, true),
  ('Circuit de Spa-Francorchamps', 'Spa-Francorchamps', 'spa-francorchamps', 'Belgian Grand Prix', 'Belgium', 'BEL', 'Stavelot', 'permanent', true, 'calendar_approved', 100, '1', 'approved', 'confirmed_2026', true, 10, 'completed', false, true),
  ('Hungaroring', 'Budapest', 'hungaroring', 'Hungarian Grand Prix', 'Hungary', 'HUN', 'Mogyorod', 'permanent', true, 'calendar_approved', 100, '1', 'approved', 'confirmed_2026', true, 11, 'completed', false, true),
  ('Circuit Zandvoort', 'Zandvoort', 'zandvoort', 'Dutch Grand Prix', 'Netherlands', 'NLD', 'Zandvoort', 'permanent', true, 'calendar_approved', 100, '1', 'approved', 'confirmed_2026', true, 12, 'completed', false, true),
  ('Autodromo Nazionale Monza', 'Monza', 'monza', 'Italian Grand Prix', 'Italy', 'ITA', 'Monza', 'permanent', true, 'calendar_approved', 100, '1', 'approved', 'confirmed_2026', true, 13, 'scheduled', false, true),
  ('Madring', 'Madrid IFEMA', 'madrid-ifema', 'Spanish Grand Prix', 'Spain', 'ESP', 'Madrid', 'semi_permanent', true, 'calendar_approved', 95, '1', 'calendar_approved', 'confirmed_2026', true, 14, 'scheduled', false, false),
  ('Baku City Circuit', 'Baku', 'baku', 'Azerbaijan Grand Prix', 'Azerbaijan', 'AZE', 'Baku', 'street', true, 'calendar_approved', 100, '1', 'approved', 'confirmed_2026', true, 15, 'scheduled', false, true),
  ('Sepang International Circuit', 'Sepang', 'sepang', 'Bahrain Grand Prix in Malaysia', 'Malaysia', 'MYS', 'Sepang', 'permanent', true, 'calendar_approved', 100, '1', 'approved', 'confirmed_2026_replacement', true, 16, 'scheduled_replacement', false, true),
  ('Marina Bay Street Circuit', 'Singapore', 'marina-bay', 'Singapore Grand Prix', 'Singapore', 'SGP', 'Singapore', 'street', true, 'calendar_approved', 100, '1', 'approved', 'confirmed_2026', true, 17, 'scheduled', false, false),
  ('Circuit of the Americas', 'Austin', 'circuit-of-the-americas', 'United States Grand Prix', 'United States', 'USA', 'Austin', 'permanent', true, 'calendar_approved', 100, '1', 'approved', 'confirmed_2026', true, 18, 'scheduled', false, true),
  ('Autodromo Hermanos Rodriguez', 'Mexico City', 'hermanos-rodriguez', 'Mexico City Grand Prix', 'Mexico', 'MEX', 'Mexico City', 'permanent', true, 'calendar_approved', 100, '1', 'approved', 'confirmed_2026', true, 19, 'scheduled', false, true),
  ('Autodromo Jose Carlos Pace', 'Interlagos', 'interlagos', 'Sao Paulo Grand Prix', 'Brazil', 'BRA', 'Sao Paulo', 'permanent', true, 'calendar_approved', 100, '1', 'approved', 'confirmed_2026', true, 20, 'scheduled', false, true),
  ('Las Vegas Strip Circuit', 'Las Vegas', 'las-vegas', 'Las Vegas Grand Prix', 'United States', 'USA', 'Las Vegas', 'street', true, 'calendar_approved', 100, '1', 'approved', 'confirmed_2026', true, 21, 'scheduled', false, false),
  ('Lusail International Circuit', 'Lusail', 'lusail', 'Qatar Grand Prix', 'Qatar', 'QAT', 'Lusail', 'permanent', true, 'calendar_approved', 100, '1', 'approved', 'confirmed_2026', true, 22, 'scheduled', false, true),
  ('Yas Marina Circuit', 'Yas Marina', 'yas-marina', 'Abu Dhabi Grand Prix', 'United Arab Emirates', 'ARE', 'Abu Dhabi', 'permanent', true, 'calendar_approved', 100, '1', 'approved', 'confirmed_2026', true, 23, 'scheduled', false, true)
on conflict (slug) do update set
  circuit_name = excluded.circuit_name,
  display_name = excluded.display_name,
  grand_prix_name = excluded.grand_prix_name,
  country = excluded.country,
  country_code = excluded.country_code,
  city = excluded.city,
  circuit_type = excluded.circuit_type,
  eligible_for_f1 = excluded.eligible_for_f1,
  eligibility_status = excluded.eligibility_status,
  eligibility_score = excluded.eligibility_score,
  fia_grade = excluded.fia_grade,
  fia_homologation_status = excluded.fia_homologation_status,
  calendar_status = excluded.calendar_status,
  is_on_2026_calendar = excluded.is_on_2026_calendar,
  calendar_round_2026 = excluded.calendar_round_2026,
  event_status_2026 = excluded.event_status_2026,
  future_candidate = excluded.future_candidate,
  replacement_track_capable = excluded.replacement_track_capable;

-- Unconfirmed game-world candidates. These are deliberately not marked as confirmed F1 events.
insert into public.tracks (
  circuit_name, display_name, slug, country, country_code, city, circuit_type,
  eligible_for_f1, eligibility_status, fia_grade, fia_homologation_status,
  calendar_status, is_on_2026_calendar, future_candidate, candidate_priority,
  candidate_readiness_rating, earliest_possible_entry_year,
  replacement_track_capable, calendar_rotation_candidate, candidacy_notes
)
values
  ('Kyalami Grand Prix Circuit', 'Kyalami', 'kyalami', 'South Africa', 'ZAF', 'Midrand', 'permanent', false, 'requires_fia_and_commercial_approval', null, 'upgrade_or_review_required', 'future_candidate', false, true, 90, 70, 2027, true, true, 'Candidate for game simulation only; not a confirmed future F1 event.'),
  ('Istanbul Park', 'Istanbul Park', 'istanbul-park', 'Turkey', 'TUR', 'Istanbul', 'permanent', false, 'requires_current_homologation_and_contract', null, 'review_required', 'future_candidate', false, true, 80, 75, 2027, true, true, 'Former F1 venue retained as a possible game-world return.'),
  ('Hockenheimring', 'Hockenheim', 'hockenheimring', 'Germany', 'DEU', 'Hockenheim', 'permanent', false, 'requires_current_homologation_and_contract', null, 'review_required', 'future_candidate', false, true, 75, 70, 2027, true, true, 'Former F1 venue retained as a possible game-world return.'),
  ('Algarve International Circuit', 'Portimao', 'portimao', 'Portugal', 'PRT', 'Portimao', 'permanent', false, 'requires_current_homologation_and_contract', null, 'review_required', 'future_candidate', false, true, 70, 75, 2027, true, true, 'Former F1 venue retained as a possible replacement or rotation event.'),
  ('Mugello Circuit', 'Mugello', 'mugello', 'Italy', 'ITA', 'Scarperia e San Piero', 'permanent', false, 'requires_current_homologation_and_contract', null, 'review_required', 'future_candidate', false, true, 65, 75, 2027, true, true, 'Former F1 venue retained as a possible replacement or rotation event.'),
  ('Buddh International Circuit', 'Buddh', 'buddh', 'India', 'IND', 'Greater Noida', 'permanent', false, 'requires_current_homologation_and_contract', null, 'review_required', 'future_candidate', false, true, 60, 60, 2028, true, true, 'Former F1 venue requiring regulatory, commercial, and homologation review.')
on conflict (slug) do update set
  future_candidate = excluded.future_candidate,
  candidate_priority = excluded.candidate_priority,
  candidate_readiness_rating = excluded.candidate_readiness_rating,
  earliest_possible_entry_year = excluded.earliest_possible_entry_year,
  candidacy_notes = excluded.candidacy_notes;

drop trigger if exists tracks_set_updated_at on public.tracks;
create trigger tracks_set_updated_at
before update on public.tracks
for each row execute function public.set_updated_at();

alter table public.tracks enable row level security;
