-- Add stable IDs when the dashboard-created tables do not already have them.
alter table public.teams
  add column if not exists id bigint generated by default as identity;

alter table public.drivers
  add column if not exists id bigint generated by default as identity;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.teams'::regclass
      and contype = 'p'
  ) then
    alter table public.teams alter column id set not null;
    alter table public.teams add constraint teams_pkey primary key (id);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.drivers'::regclass
      and contype = 'p'
  ) then
    alter table public.drivers alter column id set not null;
    alter table public.drivers add constraint drivers_pkey primary key (id);
  end if;
end
$$;

alter table public.drivers
  add column if not exists first_name text,
  add column if not exists last_name text,
  add column if not exists date_of_birth date,
  add column if not exists team_id bigint,
  add column if not exists driver_status text not null default 'active',
  add column if not exists morale integer not null default 70,
  add column if not exists fitness integer not null default 100,
  add column if not exists form integer not null default 70,
  add column if not exists marketability integer not null default 50,
  add column if not exists reputation integer not null default 50,
  add column if not exists development_rate integer not null default 50,
  add column if not exists adaptability integer not null default 50,
  add column if not exists reactions integer not null default 50,
  add column if not exists braking integer not null default 50,
  add column if not exists cornering integer not null default 50,
  add column if not exists smoothness integer not null default 50,
  add column if not exists incident_proneness integer not null default 50,
  add column if not exists injury_status text not null default 'healthy',
  add column if not exists portrait_url text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

-- Preserve existing identity data before removing spreadsheet-derived fields.
update public.drivers
set
  first_name = coalesce(first_name, split_part(driver_name, ' ', 1)),
  last_name = coalesce(
    last_name,
    nullif(substr(driver_name, length(split_part(driver_name, ' ', 1)) + 2), '')
  ),
  date_of_birth = coalesce(date_of_birth, make_date(birth_year, 1, 1))
where driver_name is not null or birth_year is not null;

-- Link team names when the teams table uses the conventional name column.
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'teams'
      and column_name = 'name'
  ) then
    execute $sql$
      update public.drivers d
      set team_id = t.id
      from public.teams t
      where d.team_id is null
        and lower(t.name) = lower(d.team)
    $sql$;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.drivers'::regclass
      and conname = 'drivers_team_id_fkey'
  ) then
    alter table public.drivers
      add constraint drivers_team_id_fkey
      foreign key (team_id) references public.teams(id)
      on delete set null;
  end if;
end
$$;

create table if not exists public.driver_contracts (
  id bigint generated by default as identity primary key,
  driver_id bigint not null references public.drivers(id) on delete cascade,
  team_id bigint references public.teams(id) on delete set null,
  start_year integer,
  end_year integer,
  base_salary_usd_millions numeric(8, 2),
  bonus_clause_strength integer,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint driver_contracts_year_order check (
    end_year is null or start_year is null or end_year >= start_year
  ),
  constraint driver_contracts_bonus_range check (
    bonus_clause_strength is null or bonus_clause_strength between 0 and 100
  )
);

create table if not exists public.driver_career_stats (
  id bigint generated by default as identity primary key,
  driver_id bigint not null references public.drivers(id) on delete cascade,
  season integer,
  starts integer not null default 0,
  wins integer not null default 0,
  world_championships integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint driver_career_stats_nonnegative check (
    starts >= 0 and wins >= 0 and world_championships >= 0
  )
);

create unique index if not exists driver_career_stats_driver_season_idx
  on public.driver_career_stats (driver_id, season)
  nulls not distinct;

create table if not exists public.driver_rating_history (
  id bigint generated by default as identity primary key,
  driver_id bigint not null references public.drivers(id) on delete cascade,
  recorded_at timestamptz not null default now(),
  season integer,
  overall_rating integer,
  pace integer,
  overtaking integer,
  defending integer,
  racecraft integer,
  wet_weather_ability integer,
  qualifying integer,
  consistency integer,
  aggression integer,
  experience_rating integer,
  potential_rating integer,
  battery_management integer,
  team_orders_understanding integer,
  reliability integer,
  tyre_management integer,
  adaptability integer,
  reactions integer,
  braking integer,
  cornering integer,
  smoothness integer
);

-- Move existing spreadsheet values into their normalized tables.
insert into public.driver_contracts (
  driver_id,
  team_id,
  start_year,
  end_year,
  base_salary_usd_millions,
  bonus_clause_strength
)
select
  id,
  team_id,
  contract_start_year,
  contract_end_year_est,
  base_salary_usd_millions,
  bonus_clause_strength
from public.drivers
where contract_start_year is not null
   or contract_end_year_est is not null
   or base_salary_usd_millions is not null
   or bonus_clause_strength is not null;

insert into public.driver_career_stats (
  driver_id,
  starts,
  wins,
  world_championships
)
select
  id,
  coalesce(career_starts, 0),
  coalesce(career_wins, 0),
  coalesce(world_championships, 0)
from public.drivers
where career_starts is not null
   or career_wins is not null
   or world_championships is not null
on conflict (driver_id, season) do nothing;

insert into public.driver_rating_history (
  driver_id,
  overall_rating,
  pace,
  overtaking,
  defending,
  racecraft,
  wet_weather_ability,
  qualifying,
  consistency,
  aggression,
  experience_rating,
  potential_rating,
  battery_management,
  team_orders_understanding,
  reliability,
  tyre_management,
  adaptability,
  reactions,
  braking,
  cornering,
  smoothness
)
select
  id,
  current_overall_rating,
  pace,
  overtaking,
  defending,
  racecraft,
  wet_weather_ability,
  qualifying,
  consistency,
  aggression,
  experience_rating,
  potential_rating,
  battery_management,
  team_orders_understanding,
  reliability,
  tyre_management,
  adaptability,
  reactions,
  braking,
  cornering,
  smoothness
from public.drivers;

alter table public.drivers
  drop column if exists age_2026,
  drop column if exists birth_year,
  drop column if exists team,
  drop column if exists driver_name,
  drop column if exists experience_level_code,
  drop column if exists salary_tier_code,
  drop column if exists contract_start_year,
  drop column if exists contract_end_year_est,
  drop column if exists base_salary_usd_millions,
  drop column if exists bonus_clause_strength,
  drop column if exists career_starts,
  drop column if exists career_wins,
  drop column if exists world_championships,
  drop column if exists current_overall_rating,
  drop column if exists pit_stop_precision;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists drivers_set_updated_at on public.drivers;
create trigger drivers_set_updated_at
before update on public.drivers
for each row execute function public.set_updated_at();

drop trigger if exists driver_contracts_set_updated_at on public.driver_contracts;
create trigger driver_contracts_set_updated_at
before update on public.driver_contracts
for each row execute function public.set_updated_at();

drop trigger if exists driver_career_stats_set_updated_at on public.driver_career_stats;
create trigger driver_career_stats_set_updated_at
before update on public.driver_career_stats
for each row execute function public.set_updated_at();

alter table public.drivers enable row level security;
alter table public.driver_contracts enable row level security;
alter table public.driver_career_stats enable row level security;
alter table public.driver_rating_history enable row level security;

create index if not exists drivers_team_id_idx on public.drivers(team_id);
create index if not exists driver_contracts_driver_id_idx on public.driver_contracts(driver_id);
create index if not exists driver_contracts_team_id_idx on public.driver_contracts(team_id);
create index if not exists driver_rating_history_driver_id_idx
  on public.driver_rating_history(driver_id, recorded_at desc);
