-- Comprehensive team profile. Ratings use a 0-100 scale unless noted otherwise.
alter table public.teams
  -- Identity and organisation
  add column if not exists short_name text,
  add column if not exists legal_name text,
  add column if not exists constructor_name text,
  add column if not exists team_code text,
  add column if not exists slug text,
  add column if not exists team_status text not null default 'active',
  add column if not exists founded_year integer,
  add column if not exists first_f1_entry_year integer,
  add column if not exists base_city text,
  add column if not exists base_country text,
  add column if not exists nationality text,
  add column if not exists owner_name text,
  add column if not exists parent_company text,
  add column if not exists ownership_type text,
  add column if not exists headquarters_name text,
  add column if not exists factory_timezone text,

  -- Branding and presentation
  add column if not exists primary_colour text,
  add column if not exists secondary_colour text,
  add column if not exists accent_colour text,
  add column if not exists text_colour text,
  add column if not exists logo_url text,
  add column if not exists small_logo_url text,
  add column if not exists car_livery_url text,
  add column if not exists team_photo_url text,
  add column if not exists website_url text,
  add column if not exists social_handle text,
  add column if not exists team_motto text,
  add column if not exists brand_personality text,

  -- Competitive identity and reputation
  add column if not exists prestige_rating integer not null default 50,
  add column if not exists reputation_rating integer not null default 50,
  add column if not exists championship_expectation_rating integer not null default 50,
  add column if not exists fanbase_rating integer not null default 50,
  add column if not exists global_popularity_rating integer not null default 50,
  add column if not exists home_market_popularity_rating integer not null default 50,
  add column if not exists media_interest_rating integer not null default 50,
  add column if not exists heritage_rating integer not null default 50,
  add column if not exists innovation_reputation_rating integer not null default 50,
  add column if not exists employer_attractiveness_rating integer not null default 50,

  -- Power-unit relationship
  add column if not exists power_unit_supplier text,
  add column if not exists power_unit_contract_start_year integer,
  add column if not exists power_unit_contract_end_year integer,
  add column if not exists is_works_team boolean not null default false,
  add column if not exists power_unit_relationship_rating integer not null default 50,
  add column if not exists power_unit_priority_rating integer not null default 50,
  add column if not exists power_unit_integration_rating integer not null default 50,

  -- Cash, budget cap, income and expenditure (USD millions)
  add column if not exists cash_balance_usd_millions numeric(12, 2) not null default 0,
  add column if not exists debt_usd_millions numeric(12, 2) not null default 0,
  add column if not exists annual_budget_usd_millions numeric(12, 2) not null default 0,
  add column if not exists budget_cap_limit_usd_millions numeric(12, 2) not null default 0,
  add column if not exists budget_cap_spent_usd_millions numeric(12, 2) not null default 0,
  add column if not exists budget_cap_committed_usd_millions numeric(12, 2) not null default 0,
  add column if not exists cost_cap_headroom_usd_millions numeric(12, 2) not null default 0,
  add column if not exists projected_season_spend_usd_millions numeric(12, 2) not null default 0,
  add column if not exists owner_funding_usd_millions numeric(12, 2) not null default 0,
  add column if not exists prize_money_usd_millions numeric(12, 2) not null default 0,
  add column if not exists sponsorship_income_usd_millions numeric(12, 2) not null default 0,
  add column if not exists merchandise_income_usd_millions numeric(12, 2) not null default 0,
  add column if not exists hospitality_income_usd_millions numeric(12, 2) not null default 0,
  add column if not exists licensing_income_usd_millions numeric(12, 2) not null default 0,
  add column if not exists commercial_bonus_income_usd_millions numeric(12, 2) not null default 0,
  add column if not exists staff_cost_usd_millions numeric(12, 2) not null default 0,
  add column if not exists driver_cost_usd_millions numeric(12, 2) not null default 0,
  add column if not exists facility_upkeep_usd_millions numeric(12, 2) not null default 0,
  add column if not exists manufacturing_cost_usd_millions numeric(12, 2) not null default 0,
  add column if not exists research_cost_usd_millions numeric(12, 2) not null default 0,
  add column if not exists travel_cost_usd_millions numeric(12, 2) not null default 0,
  add column if not exists financial_stability_rating integer not null default 50,
  add column if not exists cost_efficiency_rating integer not null default 50,
  add column if not exists financial_risk_tolerance integer not null default 50,

  -- Facility levels use 0-5; condition and efficiency use 0-100
  add column if not exists factory_level integer not null default 1,
  add column if not exists factory_condition integer not null default 100,
  add column if not exists design_centre_level integer not null default 1,
  add column if not exists design_centre_condition integer not null default 100,
  add column if not exists wind_tunnel_level integer not null default 1,
  add column if not exists wind_tunnel_condition integer not null default 100,
  add column if not exists cfd_facility_level integer not null default 1,
  add column if not exists cfd_facility_condition integer not null default 100,
  add column if not exists simulator_level integer not null default 1,
  add column if not exists simulator_condition integer not null default 100,
  add column if not exists manufacturing_centre_level integer not null default 1,
  add column if not exists manufacturing_centre_condition integer not null default 100,
  add column if not exists quality_control_level integer not null default 1,
  add column if not exists quality_control_condition integer not null default 100,
  add column if not exists suspension_test_rig_level integer not null default 1,
  add column if not exists suspension_test_rig_condition integer not null default 100,
  add column if not exists car_part_test_centre_level integer not null default 1,
  add column if not exists car_part_test_centre_condition integer not null default 100,
  add column if not exists race_simulation_centre_level integer not null default 1,
  add column if not exists race_simulation_centre_condition integer not null default 100,
  add column if not exists scouting_department_level integer not null default 1,
  add column if not exists medical_facility_level integer not null default 1,
  add column if not exists staff_facilities_level integer not null default 1,
  add column if not exists team_hub_level integer not null default 1,
  add column if not exists hospitality_facility_level integer not null default 1,
  add column if not exists facility_capacity_rating integer not null default 50,
  add column if not exists facility_efficiency_rating integer not null default 50,
  add column if not exists facility_energy_efficiency_rating integer not null default 50,
  add column if not exists facility_upgrade_speed_rating integer not null default 50,

  -- Research, design and manufacturing capability
  add column if not exists research_capacity_rating integer not null default 50,
  add column if not exists design_capacity_rating integer not null default 50,
  add column if not exists manufacturing_capacity_rating integer not null default 50,
  add column if not exists manufacturing_speed_rating integer not null default 50,
  add column if not exists manufacturing_quality_rating integer not null default 50,
  add column if not exists quality_assurance_rating integer not null default 50,
  add column if not exists prototype_speed_rating integer not null default 50,
  add column if not exists upgrade_success_rate_rating integer not null default 50,
  add column if not exists development_efficiency_rating integer not null default 50,
  add column if not exists development_iteration_speed_rating integer not null default 50,
  add column if not exists regulation_research_rating integer not null default 50,
  add column if not exists knowledge_retention_rating integer not null default 50,
  add column if not exists technical_data_quality_rating integer not null default 50,
  add column if not exists correlation_accuracy_rating integer not null default 50,
  add column if not exists intellectual_property_strength_rating integer not null default 50,

  -- Component-specific technical baselines
  add column if not exists front_wing_design_rating integer not null default 50,
  add column if not exists rear_wing_design_rating integer not null default 50,
  add column if not exists floor_design_rating integer not null default 50,
  add column if not exists sidepod_design_rating integer not null default 50,
  add column if not exists chassis_design_rating integer not null default 50,
  add column if not exists suspension_design_rating integer not null default 50,
  add column if not exists brake_system_rating integer not null default 50,
  add column if not exists cooling_system_rating integer not null default 50,
  add column if not exists gearbox_integration_rating integer not null default 50,
  add column if not exists ers_integration_rating integer not null default 50,
  add column if not exists electronics_integration_rating integer not null default 50,
  add column if not exists weight_reduction_rating integer not null default 50,
  add column if not exists drag_reduction_rating integer not null default 50,
  add column if not exists drs_efficiency_rating integer not null default 50,
  add column if not exists low_speed_downforce_rating integer not null default 50,
  add column if not exists medium_speed_downforce_rating integer not null default 50,
  add column if not exists high_speed_downforce_rating integer not null default 50,
  add column if not exists dirty_air_performance_rating integer not null default 50,
  add column if not exists tyre_preservation_rating integer not null default 50,
  add column if not exists fuel_efficiency_rating integer not null default 50,
  add column if not exists component_reliability_rating integer not null default 50,

  -- Race-weekend operations
  add column if not exists race_strategy_rating integer not null default 50,
  add column if not exists qualifying_strategy_rating integer not null default 50,
  add column if not exists tyre_strategy_rating integer not null default 50,
  add column if not exists weather_forecasting_rating integer not null default 50,
  add column if not exists safety_car_response_rating integer not null default 50,
  add column if not exists pit_stop_speed_rating integer not null default 50,
  add column if not exists pit_stop_consistency_rating integer not null default 50,
  add column if not exists pit_stop_error_resistance_rating integer not null default 50,
  add column if not exists garage_operations_rating integer not null default 50,
  add column if not exists setup_accuracy_rating integer not null default 50,
  add column if not exists telemetry_analysis_rating integer not null default 50,
  add column if not exists race_engineering_rating integer not null default 50,
  add column if not exists incident_response_rating integer not null default 50,
  add column if not exists repair_speed_rating integer not null default 50,
  add column if not exists logistics_rating integer not null default 50,
  add column if not exists operational_reliability_rating integer not null default 50,
  add column if not exists protest_and_rules_rating integer not null default 50,

  -- Personnel, culture and internal stability
  add column if not exists staff_morale integer not null default 70,
  add column if not exists driver_morale integer not null default 70,
  add column if not exists board_confidence integer not null default 70,
  add column if not exists team_cohesion_rating integer not null default 50,
  add column if not exists leadership_rating integer not null default 50,
  add column if not exists communication_rating integer not null default 50,
  add column if not exists recruitment_rating integer not null default 50,
  add column if not exists staff_development_rating integer not null default 50,
  add column if not exists driver_development_rating integer not null default 50,
  add column if not exists retention_rating integer not null default 50,
  add column if not exists workplace_quality_rating integer not null default 50,
  add column if not exists political_stability_rating integer not null default 50,
  add column if not exists internal_pressure_rating integer not null default 50,
  add column if not exists blame_culture_rating integer not null default 50,
  add column if not exists innovation_culture_rating integer not null default 50,
  add column if not exists risk_management_rating integer not null default 50,

  -- Commercial operation
  add column if not exists commercial_strength_rating integer not null default 50,
  add column if not exists sponsor_attractiveness_rating integer not null default 50,
  add column if not exists sponsor_satisfaction_rating integer not null default 70,
  add column if not exists sponsor_activation_rating integer not null default 50,
  add column if not exists merchandise_strength_rating integer not null default 50,
  add column if not exists hospitality_strength_rating integer not null default 50,
  add column if not exists digital_engagement_rating integer not null default 50,
  add column if not exists media_management_rating integer not null default 50,
  add column if not exists crisis_management_rating integer not null default 50,
  add column if not exists sustainability_rating integer not null default 50,

  -- Current-season objectives and state
  add column if not exists current_season integer,
  add column if not exists constructor_position integer,
  add column if not exists constructor_points numeric(10, 2) not null default 0,
  add column if not exists target_constructor_position integer,
  add column if not exists minimum_constructor_position integer,
  add column if not exists target_points numeric(10, 2),
  add column if not exists target_race_wins integer not null default 0,
  add column if not exists target_podiums integer not null default 0,
  add column if not exists target_q3_appearances integer not null default 0,
  add column if not exists target_budget_balance_usd_millions numeric(12, 2),
  add column if not exists season_progress_rating integer not null default 50,
  add column if not exists board_patience_rating integer not null default 50,
  add column if not exists job_security_rating integer not null default 70,
  add column if not exists recent_form_rating integer not null default 50,
  add column if not exists momentum_rating integer not null default 50,
  add column if not exists championship_contender boolean not null default false,
  add column if not exists rebuilding_team boolean not null default false,

  -- Current-season operational totals
  add column if not exists season_races integer not null default 0,
  add column if not exists season_wins integer not null default 0,
  add column if not exists season_podiums integer not null default 0,
  add column if not exists season_poles integer not null default 0,
  add column if not exists season_fastest_laps integer not null default 0,
  add column if not exists season_dnfs integer not null default 0,
  add column if not exists season_double_points_finishes integer not null default 0,
  add column if not exists season_penalty_points integer not null default 0,
  add column if not exists season_fines_usd_millions numeric(12, 2) not null default 0,

  -- Historical record
  add column if not exists all_time_race_starts integer not null default 0,
  add column if not exists all_time_wins integer not null default 0,
  add column if not exists all_time_podiums integer not null default 0,
  add column if not exists all_time_poles integer not null default 0,
  add column if not exists all_time_fastest_laps integer not null default 0,
  add column if not exists constructors_championships integer not null default 0,
  add column if not exists drivers_championships integer not null default 0,
  add column if not exists last_race_win_year integer,
  add column if not exists last_championship_year integer,
  add column if not exists best_constructor_finish integer,

  -- AI team-building and race behaviour
  add column if not exists ai_aggression integer not null default 50,
  add column if not exists ai_risk_tolerance integer not null default 50,
  add column if not exists ai_spending_aggression integer not null default 50,
  add column if not exists ai_driver_loyalty integer not null default 50,
  add column if not exists ai_staff_loyalty integer not null default 50,
  add column if not exists ai_youth_preference integer not null default 50,
  add column if not exists ai_star_driver_preference integer not null default 50,
  add column if not exists ai_facility_priority integer not null default 50,
  add column if not exists ai_research_priority integer not null default 50,
  add column if not exists ai_reliability_priority integer not null default 50,
  add column if not exists ai_aerodynamics_priority integer not null default 50,
  add column if not exists ai_race_strategy_aggression integer not null default 50,
  add column if not exists ai_contract_negotiation_rating integer not null default 50,
  add column if not exists ai_long_term_planning integer not null default 50,
  add column if not exists ai_sponsor_priority integer not null default 50,

  -- Governance, compliance and metadata
  add column if not exists cost_cap_compliance_rating integer not null default 100,
  add column if not exists technical_compliance_rating integer not null default 100,
  add column if not exists sporting_compliance_rating integer not null default 100,
  add column if not exists active_investigation_count integer not null default 0,
  add column if not exists grid_penalty_risk_rating integer not null default 0,
  add column if not exists notes text,
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists teams_team_code_unique_idx
  on public.teams (team_code)
  where team_code is not null;

create unique index if not exists teams_slug_unique_idx
  on public.teams (slug)
  where slug is not null;

create index if not exists teams_constructor_position_idx
  on public.teams (constructor_position);

create index if not exists teams_team_status_idx
  on public.teams (team_status);

drop trigger if exists teams_set_updated_at on public.teams;
create trigger teams_set_updated_at
before update on public.teams
for each row execute function public.set_updated_at();

alter table public.teams enable row level security;
