alter table public.staff
  add column if not exists primary_specialism text,
  add column if not exists front_wing_expertise integer not null default 50,
  add column if not exists rear_wing_expertise integer not null default 50,
  add column if not exists floor_expertise integer not null default 50,
  add column if not exists sidepod_expertise integer not null default 50,
  add column if not exists chassis_expertise integer not null default 50,
  add column if not exists suspension_expertise integer not null default 50,
  add column if not exists brake_expertise integer not null default 50,
  add column if not exists power_unit_expertise integer not null default 50,
  add column if not exists gearbox_expertise integer not null default 50,
  add column if not exists ers_expertise integer not null default 50,
  add column if not exists cooling_expertise integer not null default 50,
  add column if not exists electronics_expertise integer not null default 50,
  add column if not exists diagnostics_rating integer not null default 50,
  add column if not exists repair_speed_rating integer not null default 50,
  add column if not exists setup_optimisation_rating integer not null default 50;

alter table public.staff
  add constraint staff_front_wing_expertise_range check (front_wing_expertise between 0 and 100),
  add constraint staff_rear_wing_expertise_range check (rear_wing_expertise between 0 and 100),
  add constraint staff_floor_expertise_range check (floor_expertise between 0 and 100),
  add constraint staff_sidepod_expertise_range check (sidepod_expertise between 0 and 100),
  add constraint staff_chassis_expertise_range check (chassis_expertise between 0 and 100),
  add constraint staff_suspension_expertise_range check (suspension_expertise between 0 and 100),
  add constraint staff_brake_expertise_range check (brake_expertise between 0 and 100),
  add constraint staff_power_unit_expertise_range check (power_unit_expertise between 0 and 100),
  add constraint staff_gearbox_expertise_range check (gearbox_expertise between 0 and 100),
  add constraint staff_ers_expertise_range check (ers_expertise between 0 and 100),
  add constraint staff_cooling_expertise_range check (cooling_expertise between 0 and 100),
  add constraint staff_electronics_expertise_range check (electronics_expertise between 0 and 100),
  add constraint staff_diagnostics_rating_range check (diagnostics_rating between 0 and 100),
  add constraint staff_repair_speed_rating_range check (repair_speed_rating between 0 and 100),
  add constraint staff_setup_optimisation_rating_range check (setup_optimisation_rating between 0 and 100);
